#!/bin/bash

cd ../src
python frontend.py > flask_logs.txt 2>&1 &
sleep 1
python catalog_server.py catalog.csv > flask_logs.txt 2>&1 &
process_id=$!
sleep 1
python order_server.py > flask_logs.txt 2>&1 &
sleep 1
cd ../tests
# The first test
python test1.py
# Kill the catalog server to restart it with a different catalog for the next test
kill -9 $process_id
cd ../src
# Restarting the catalog server with a different catalog for 2nd and 3rd tests
python catalog_server.py catalog2.csv > flask_logs.txt 2>&1 &
process_id=$!
sleep 1
cd ../tests
# 2nd Test
python test2.py
# 3rd Test
python test3.py 1 & python test3.py 2 &
sleep 2
# Kill catalog server
kill -9 $process_id
cd ../src
# Restart for 4th test
python catalog_server.py catalog3.csv > flask_logs.txt 2>&1 &
process_id=$!
sleep 1
cd ../tests
# 4th Test
python test4.py 1 &
test4_id1=$!
python test4.py 2 &
test4_id2=$!
sleep 2
# Kill catalog server
kill -9 $process_id
cd ../src
# Restart for 5th test
python catalog_server.py catalog3.csv > flask_logs.txt 2>&1 &
process_id=$!
sleep 2
cd ../tests
# 5th Test
python test5.py 1 & python test5.py 2 & python test5.py 3 &









